[global]
   workgroup = WORKGROUP
   server string = Samba Server
   security = user
   map to guest = Bad User

[shared]
   path = /home/ronak/shared
   browseable = yes
   read only = no
   writable = yes
   guest ok = yes

[admin]
   path = /home/ronak/admin
   browseable = yes
   read only = no
   writable = yes
   guest ok = no
   valid users = ronak
